package com.anirban.entity;

public enum NotificationType {

    APPLICATION_STATUS,
    NEW_APPLICATION,
    APPLICATION_WITHDRAWN,

    INTERVIEW_SCHEDULED,
    INTERVIEW_RESCHEDULED,
    INTERVIEW_CANCELLED,
    INTERVIEW_COMPLETED,

    OFFER_SENT,
    OFFER_ACCEPTED,
    OFFER_REJECTED,
    OFFER_WITHDRAWN
}